<?php
/**
* @file
* Enables jQuery Cookie from Drupal's core System Module
*/

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function jq_cookie_help($path, $arg) {
  switch ($path) {
    case "admin/help#jq_cookie":
      $file_path = drupal_get_path('module', 'jq_cookie') . '/help/index.html';
      return $msg . '<br><br><hr> ' . file_get_contents($file_path);
      break;
  }
}

/**
 * Implements hook_page_alter().
 *
 * Enables jquery.cookie, which is included in Drupal 7's core.
 */
function jq_cookie_page_alter(&$page) {

  // Enable jQuery Cookie and put it on every page
  drupal_add_library('system', 'jquery.cookie');

}
